apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/jenkinsci.git
    path: helm-charts/tree/main/charts/jenkins
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
