apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NeilCic/devops-lesson8-argocd.git
    path: homework
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
